# Analyzing Personality Domain Evaluation üåä

Using the  **Persona-Predict V2** üß† service to assess the nuanced understanding of **Brazilian Portuguese** üáßüá∑ in each of the **Big Five** personality domains. For more information about the service visit: [docs.neuroquest.ai/persona-predict](https://docs.neuroquest.ai/persona-predict/)

The scores for the traits follow the [IPIP](https://ipip.ori.org/) standard. Where:

- If the score is below 45: It is classified as a 'low' score.
- If the score is between 45 and 55: It is classified as an 'average' score.
- If the score is above 55: It is classified as a 'high' score.

For texts in **English**, the **raw_score** value will be equal to the **percentile**, as calibration is not required 
for the English-speaking population. If you have any doubts about interpreting the results, please consult a psychologist 
specializing in personality theory.

If the graphics are not rendered üö´, use the address:

  - [View in NBViewer](https://nbviewer.org/github/NeuroQuestAi/neuroquest-examples/blob/main/products/persona-predict/notebooks/Persona-Predict-Eval-PT-BR.ipynb?flush_cache=true)

In [1]:
import os

import pandas as pd
import utility as U

In [ ]:
NQ_USER = os.getenv("NQ_USER")
NQ_PASSWORD = os.getenv("NQ_PASSWORD")

In [3]:
assert NQ_USER is not None, "set the user"
assert NQ_PASSWORD is not None, "set the password"

In [4]:
def create_analysis(name: str, essay: str, domain: str, level: str) -> dict:
    analysis = U.api_predict_create(
        token=U.api_login(user=NQ_USER, password=NQ_PASSWORD).get("data").get("token"),
        data={
            "name": name,
            "essay": essay,
            "domain": domain,
            "task": False,
        },
        save_result=False,
    )
    U.api_save_result_domain(data=analysis, domain=domain, level=level)
    return analysis

## 1. Big-Five Openness Domains üßë‚Äçüé® 

- Evaluate the capture of nuances of Openness to Experience texts.

### 1.1 Capture Openness High

In [5]:
essay_pt_br_O_high = """
A vida √© um vasto campo de possibilidades, onde cada novo dia √© uma tela em branco, pronta para ser preenchida com cores, 
formas e ideias √∫nicas. Adoro explorar o desconhecido, mergulhando em livros que me transportam para mundos distantes, 
experimentando sabores ex√≥ticos e permitindo que minha mente vagueie por conceitos abstratos e filos√≥ficos. A curiosidade 
√© minha guia, sempre me levando a questionar o status quo e a buscar novas perspectivas. Acredito que a verdadeira beleza 
reside na diversidade das experi√™ncias e na liberdade de reinventar a pr√≥pria exist√™ncia a cada instante.
"""

In [6]:
analysis = create_analysis(
    name="Openness",
    essay=" ".join(essay_pt_br_O_high.split()),
    domain="O",
    level="high",
)

In [11]:
score_openness_facets = (
    analysis.get("data")
    .get("person")
    .get("analysis")
    .get("personalities")[0]
    .get("openness")
    .get("traits")
)
pd.DataFrame(score_openness_facets, columns=["name", "raw_score", "percentile", "confidence"])

                    name  raw_score  percentile  confidence
0             Imagina√ß√£o  77.129528   83.294027   98.596553
1  Interesses Art√≠sticos  76.043026   78.684100   98.533283
2            Emotividade  80.510864   79.370827   98.658241
3     Desejo de Aventura  78.512854   80.713511   98.504548
4       Intelectualidade  81.829785   82.645468   98.594099
5            Liberalismo  74.807825   76.139942   98.647199

### 1.2 Capture Openness Low

In [12]:
essay_pt_br_O_low = """
Prefiro manter as coisas do jeito que s√£o, sem muitas mudan√ßas ou surpresas. A rotina traz seguran√ßa e me permite 
focar no que realmente importa. valorizo a tradi√ß√£o e as pr√°ticas que j√° foram testadas e comprovadas ao longo do tempo. 
N√£o vejo necessidade de explorar coisas novas ou arriscar, quando j√° sei o que funciona bem para mim. Gosto de seguir 
um plano e evitar distra√ß√µes, focando no que √© pr√°tico e eficiente. a vida √© melhor quando √© simples e previs√≠vel.
"""

In [13]:
analysis = create_analysis(
    name="Openness", essay=" ".join(essay_pt_br_O_low.split()), domain="O", level="low"
)

In [14]:
score_openness_facets = (
    analysis.get("data")
    .get("person")
    .get("analysis")
    .get("personalities")[0]
    .get("openness")
    .get("traits")
)
pd.DataFrame(score_openness_facets, columns=["name", "raw_score", "percentile", "confidence"])

                    name  raw_score  percentile  confidence
0             Imagina√ß√£o  29.782847   36.052711   96.419379
1  Interesses Art√≠sticos  30.323396   32.982977   96.619580
2            Emotividade  31.474606   30.324194   96.728855
3     Desejo de Aventura  21.801954   23.992912   95.106231
4       Intelectualidade  28.288366   29.093110   96.181217
5            Liberalismo  25.881939   27.278110   95.549525

### 1.3 Capture Openness Average

In [15]:
essay_pt_br_O_avg = """
√Äs vezes, tenho momentos de imagina√ß√£o, mas n√£o √© algo que me define completamente. Gosto de 
deixar minha mente vagar de vez em quando, mas tamb√©m sei que h√° muitos outros aspectos que 
moldam quem sou. Reconhe√ßo a import√¢ncia da arte, mas n√£o √© algo que considero fundamental na 
minha vida. Aprecio a beleza das express√µes art√≠sticas, mas sei que minha felicidade n√£o depende disso. 
√Äs vezes, sinto minhas emo√ß√µes intensamente, mas n√£o √© sempre o caso. H√° momentos em que sou mais 
reflexivo e racional, tentando ver as situa√ß√µes de forma equilibrada. Gosto de ter uma mistura de 
rotina e variedade; n√£o tenho uma prefer√™ncia forte por um ou outro. A rotina me proporciona estabilidade, 
mas tamb√©m sei que a variedade traz novas experi√™ncias e aprendizados. √Äs vezes gosto de ler material desafiador, 
mas minha prefer√™ncia pode variar dependendo do tipo de conte√∫do e do meu estado de esp√≠rito.
"""

In [16]:
analysis = create_analysis(
    name="Openness", essay=" ".join(essay_pt_br_O_avg.split()), domain="O", level="avg"
)

In [17]:
score_openness_facets = (
    analysis.get("data")
    .get("person")
    .get("analysis")
    .get("personalities")[0]
    .get("openness")
    .get("traits")
)
pd.DataFrame(score_openness_facets, columns=["name", "raw_score", "percentile", "confidence"])

                    name  raw_score  percentile  confidence
0             Imagina√ß√£o  63.272126   69.516006   97.843395
1  Interesses Art√≠sticos  57.702311   60.378202   97.676131
2            Emotividade  61.711897   60.572862   97.873470
3     Desejo de Aventura  56.625288   58.804109   97.613841
4       Intelectualidade  62.512159   63.340205   97.843888
5            Liberalismo  58.969294   60.371109   97.737347

## 2. Big-Five Conscientiousness Domains üßë‚Äçüî¨

- Evaluate the capture of nuances of Conscientiousness texts.

### 2.1 Capture Conscientiousness High

In [18]:
essay_pt_br_C_high = """
Sou uma pessoa que leva a s√©rio minhas responsabilidades. Gosto de manter tudo organizado, desde meu espa√ßo de trabalho 
at√© minhas tarefas di√°rias. planejo com anteced√™ncia e me esfor√ßo para cumprir todas as metas que estabele√ßo para mim. 
Acredito que a disciplina √© a chave para o sucesso, por isso procuro sempre manter o foco e evitar distra√ß√µes. Quando me 
comprometo com algo, dou o meu melhor para entregar um trabalho bem feito e dentro do prazo. Para mim, ser confi√°vel e 
cumprir o que prometo √© fundamental.
"""

In [19]:
analysis = create_analysis(
    name="Conscientiousness",
    essay=" ".join(essay_pt_br_C_high.split()),
    domain="C",
    level="high",
)

In [20]:
score_conscientiousness_facets = (
    analysis.get("data")
    .get("person")
    .get("analysis")
    .get("personalities")[0]
    .get("conscientiousness")
    .get("traits")
)
pd.DataFrame(
    score_conscientiousness_facets, columns=["name", "raw_score", "percentile", "confidence"]
)

               name  raw_score  percentile  confidence
0     Auto-Efic√°cia  71.299056   73.721955   98.516057
1       Organiza√ß√£o  68.885264   76.626956   98.511230
2  Responsabilidade  69.444886   74.430287   98.453051
3      Determina√ß√£o  68.199749   72.185670   98.395386
4   Auto-Disciplina  69.455824   78.468552   98.451434
5           Cautela  69.605304   76.802451   98.459612

### 2.2 Capture Conscientiousness Low

In [21]:
essay_pt_br_C_low = """
Costumo ser mais espont√¢neo e n√£o me prendo muito a rotinas ou planejamentos. Prefiro viver o momento, e a ideia de seguir 
uma agenda r√≠gida n√£o me atrai. √Ås vezes, acabo deixando tarefas para depois e, confesso, nem sempre sou t√£o organizado 
quanto gostaria. N√£o me preocupo tanto com prazos ou com manter tudo em ordem, pois acredito que as coisas se resolvem 
eventualmente. Prefiro a liberdade de seguir o fluxo do que me prender a regras ou expectativas r√≠gidas.
"""

In [22]:
analysis = create_analysis(
    name="Conscientiousness",
    essay=" ".join(essay_pt_br_C_low.split()),
    domain="C",
    level="low",
)

In [23]:
score_conscientiousness_facets = (
    analysis.get("data")
    .get("person")
    .get("analysis")
    .get("personalities")[0]
    .get("conscientiousness")
    .get("traits")
)
pd.DataFrame(score_conscientiousness_facets, columns=["name", "raw_score", "percentile", "confidence"])

               name  raw_score  percentile  confidence
0     Auto-Efic√°cia  41.370792   43.784086   96.798863
1       Organiza√ß√£o  31.832982   39.523070   92.567167
2  Responsabilidade  31.271693   36.203329   82.291517
3      Determina√ß√£o  41.654193   45.572404   96.928100
4   Auto-Disciplina  39.917560   49.251351   96.586744
5           Cautela  39.789422   46.919867   96.828384

### 2.3 Capture Conscientiousness Average

In [24]:
essay_pt_br_C_avg = """
Eu me considero uma pessoa organizada, mas sem exageros. Gosto de planejar as coisas, mas tamb√©m sei ser 
flex√≠vel quando necess√°rio. Cumpro com minhas responsabilidades e me esfor√ßo para fazer um bom trabalho, 
mas n√£o sinto a necessidade de controlar todos os detalhes o tempo todo. Prefiro manter um equil√≠brio; 
gosto de estar preparado e manter um certo n√≠vel de disciplina, mas tamb√©m sei que, √†s vezes, √© preciso 
adaptar-se e improvisar.
"""

In [25]:
analysis = create_analysis(
    name="Conscientiousness",
    essay=" ".join(essay_pt_br_C_avg.split()),
    domain="C",
    level="avg",
)

In [27]:
score_conscientiousness_facets = (
    analysis.get("data")
    .get("person")
    .get("analysis")
    .get("personalities")[0]
    .get("conscientiousness")
    .get("traits")
)
pd.DataFrame(score_conscientiousness_facets, columns=["name", "raw_score", "percentile", "confidence"])

               name  raw_score  percentile  confidence
0     Auto-Efic√°cia  51.976293   54.452072   97.823179
1       Organiza√ß√£o  45.958285   53.903910   97.616327
2  Responsabilidade  46.647930   51.640537   97.343321
3      Determina√ß√£o  51.257128   55.672690   97.774092
4   Auto-Disciplina  51.185683   60.524864   97.778266
5           Cautela  51.009290   58.193899   97.819353

## 3. Big-Five Extraversion Domains üï∫üíÉ

- Evaluate the capture of nuances of Extraversion texts.

### 3.1 Capture Extraversion High

In [28]:
essay_pt_br_E_high = """
Cara, eu curto demais estar com a galera! A vibe de estar com a turma me d√° um g√°s, sabe? Seja numa festa, 
num rol√™ ou at√© trocando ideia no dia a dia, t√¥ sempre na pilha de trocar uma ideia e conhecer gente nova. 
Quanto mais gente, mais divertido! Gosto de puxar papo, soltar umas piadas e fazer a galera dar risada. 
Ficar sozinho? N√£o √© muito a minha praia, prefiro mil vezes estar no meio da bagun√ßa, vivendo o agito. 
Pra mim, qualquer dia fica melhor quando tem gente por perto, seja no trampo ou s√≥ curtindo mesmo!
"""

In [29]:
analysis = create_analysis(
    name="Extraversion",
    essay=" ".join(essay_pt_br_E_high.split()),
    domain="E",
    level="high",
)

In [31]:
score_extraversion_facets = (
    analysis.get("data")
    .get("person")
    .get("analysis")
    .get("personalities")[0]
    .get("extraversion")
    .get("traits")
)
pd.DataFrame(score_extraversion_facets, columns=["name", "raw_score", "percentile", "confidence"])

                 name  raw_score  percentile  confidence
0            Simpatia  67.056527   73.454102   98.495745
1       Sociabilidade  69.288674   72.624014   98.550597
2       Assertividade  65.073831   66.636843   98.448864
3  N√≠vel de Atividade  62.203168   64.788827   98.363288
4  Busca de Excita√ß√£o  67.612793   57.282933   98.508400
5           Bom Humor  64.149970   72.252783   98.417816

### 3.2 Capture Conscientiousness Low

In [32]:
essay_pt_br_E_low = """
Eu prefiro passar mais tempo sozinho ou com um c√≠rculo pequeno de amigos pr√≥ximos. Intera√ß√µes sociais grandes 
e eventos movimentados n√£o s√£o exatamente o meu forte. Gosto de ambientes mais calmos e de ter tempo para refletir 
ou me dedicar a atividades pessoais. N√£o me sinto confort√°vel sendo o centro das aten√ß√µes e geralmente evito situa√ß√µes 
que exigem muita socializa√ß√£o. Para mim, a satisfa√ß√£o vem de momentos tranquilos e de conex√µes mais √≠ntimas, onde 
posso realmente me sentir √† vontade.
"""

In [33]:
analysis = create_analysis(
    name="Extraversion",
    essay=" ".join(essay_pt_br_E_low.split()),
    domain="E",
    level="low",
)

In [35]:
score_extraversion_facets = (
    analysis.get("data")
    .get("person")
    .get("analysis")
    .get("personalities")[0]
    .get("extraversion")
    .get("traits")
)
pd.DataFrame(score_extraversion_facets, columns=["name", "raw_score", "percentile", "confidence"])

                 name  raw_score  percentile  confidence
0            Simpatia  27.530017   33.947769   96.550924
1       Sociabilidade  30.352237   33.692591   96.856893
2       Assertividade  28.297352   29.913158   96.564025
3  N√≠vel de Atividade  27.891810   30.111212   96.535132
4  Busca de Excita√ß√£o  28.083773   17.647566   96.586873
5           Bom Humor  30.663125   38.693026   96.867483

### 3.3 Capture Conscientiousness Average

In [36]:
essay_pt_br_E_avg = """
Eu valorizo bastante as intera√ß√µes sociais e aprecio a companhia de outras pessoas, mas n√£o sinto a necessidade de 
estar sempre no centro das aten√ß√µes. Gosto de participar de conversas e eventos, mas tamb√©m valorizo meu tempo pessoal 
e momentos de reflex√£o. Embora eu me sinta confort√°vel em ambientes sociais e esteja aberto a novas conex√µes, encontro 
um equil√≠brio saud√°vel entre minha vida social e momentos de tranquilidade. Para mim, √© importante manter uma abordagem 
equilibrada, desfrutando tanto das oportunidades de socializa√ß√£o quanto dos per√≠odos de introspec√ß√£o e descanso.
"""

In [37]:
analysis = create_analysis(
    name="Extraversion",
    essay=" ".join(essay_pt_br_E_avg.split()),
    domain="E",
    level="avg",
)

In [38]:
score_extraversion_facets = (
    analysis.get("data")
    .get("person")
    .get("analysis")
    .get("personalities")[0]
    .get("extraversion")
    .get("traits")
)
pd.DataFrame(score_extraversion_facets, columns=["name", "raw_score", "percentile", "confidence"])

                 name  raw_score  percentile  confidence
0            Simpatia  49.415382   55.821988   97.922453
1       Sociabilidade  52.933336   56.235558   98.099024
2       Assertividade  48.868718   50.162777   97.756141
3  N√≠vel de Atividade  48.688542   51.257052   97.798715
4  Busca de Excita√ß√£o  53.286828   42.996699   97.977703
5           Bom Humor  51.177030   59.225849   97.962775

## 4. Big-Five Agreeableness Domains üôãüß°

- Evaluate the capture of nuances of Agreeableness texts.

### 4.1 Capture Agreeableness High

In [39]:
essay_pt_br_A_high = """
Eu amo estar ao lado das pessoas, ajudar apoiar, cuidar e celebrar suas conquistas. Sei que o mundo pode 
ser um lugar desafiador, ent√£o fa√ßo quest√£o de ser uma fonte de paz e tranquilidade. Eu sempre tento 
iluminar os momentos sombrios com palavras de encorajamento e fazer com que todos saibam que podem 
contar comigo, seja qual for a situa√ß√£o. sou algu√©m que vive com o cora√ß√£o aberto, sempre disposto a dar 
o melhor de mim para que o mundo ao meu redor seja um lugar mais leve e gentil. 
"""

In [40]:
analysis = create_analysis(
    name="Agreeableness",
    essay=" ".join(essay_pt_br_A_high.split()),
    domain="A",
    level="high",
)

In [41]:
score_agreeableness_facets = (
    analysis.get("data")
    .get("person")
    .get("analysis")
    .get("personalities")[0]
    .get("agreeableness")
    .get("traits")
)
pd.DataFrame(score_agreeableness_facets, columns=["name", "raw_score", "percentile", "confidence"])

         name  raw_score  percentile  confidence
0   Confian√ßa  59.672594   64.961691   98.248036
1  Moralidade  57.673137   60.940976   98.102958
2   Altru√≠smo  57.821561   61.624873   98.208179
3  Coopera√ß√£o  61.663137   66.947485   98.248757
4    Mod√©stia  60.975063   56.102789   98.256776
5     Empatia  61.257239   61.943433   98.296135

### 4.2 Capture Agreeableness Low

In [42]:
essay_pt_br_A_low = """
Honestamente, eu n√£o sou o tipo de pessoa que se preocupa muito em agradar os outros. N√£o √© que eu queira ser 
rude ou criar conflitos, mas simplesmente n√£o vejo sentido em perder tempo tentando agradar todo mundo. Prefiro 
ser direto e resolver as coisas de forma pr√°tica, sem rodeios. Socialmente, sou mais reservado e n√£o costumo buscar 
muitas amizades ou encontros. Valorizo minha independ√™ncia e, francamente, a ideia de ficar constantemente me preocupando 
com o que os outros pensam ou precisam n√£o √© algo que me atraia.
"""

In [43]:
analysis = create_analysis(
    name="Agreeableness",
    essay=" ".join(essay_pt_br_A_low.split()),
    domain="A",
    level="low",
)

In [44]:
score_agreeableness_facets = (
    analysis.get("data")
    .get("person")
    .get("analysis")
    .get("personalities")[0]
    .get("agreeableness")
    .get("traits")
)
pd.DataFrame(score_agreeableness_facets, columns=["name", "raw_score", "percentile", "confidence"])

         name  raw_score  percentile  confidence
0   Confian√ßa  36.708865   41.865380   97.183902
1  Moralidade  33.908552   37.196813   97.047184
2   Altru√≠smo  36.452922   40.196783   97.293485
3  Coopera√ß√£o  33.667032   39.526962   97.121217
4    Mod√©stia  34.192816   28.825179   97.151715
5     Empatia  38.460786   39.152032   97.433688

### 4.3 Capture Agreeableness Average

In [45]:
essay_pt_br_A_avg = """
Sou uma pessoa que realmente se importa com os outros. Gosto de ajudar, de ouvir, e acredito que o mundo 
fica melhor quando as pessoas se tratam com bondade e respeito. Procuro sempre entender o ponto de vista 
das pessoas ao meu redor e fa√ßo quest√£o de criar um ambiente harmonioso onde todos se sintam √† vontade.
Em resumo, sou algu√©m que acredita na gentileza como uma for√ßa poderosa. Estar l√° para as pessoas ao meu redor 
√© algo natural para mim, e sinto uma enorme satisfa√ß√£o em contribuir para que todos se sintam bem e respeitados.
"""

In [46]:
analysis = create_analysis(
    name="Agreeableness",
    essay=" ".join(essay_pt_br_A_avg.split()),
    domain="A",
    level="avg",
)

In [47]:
score_agreeableness_facets = (
    analysis.get("data")
    .get("person")
    .get("analysis")
    .get("personalities")[0]
    .get("agreeableness")
    .get("traits")
)
pd.DataFrame(score_agreeableness_facets, columns=["name", "raw_score", "percentile", "confidence"])

         name  raw_score  percentile  confidence
0   Confian√ßa  49.538209   54.775166   97.931324
1  Moralidade  46.316683   49.603257   97.745631
2   Altru√≠smo  47.400066   51.134372   97.877038
3  Coopera√ß√£o  47.882868   53.525805   97.843678
4    Mod√©stia  48.716455   43.099721   97.870599
5     Empatia  48.528295   49.227224   97.902994

## 5. Big-Five Neuroticism Domains üôÖüí¢

- Evaluate the capture of nuances of Neuroticism texts.

### 5.1 Capture Neuroticism High

In [48]:
essay_pt_br_N_high = """
Fico irritado muito facilmente; pequenos contratempos podem me deixar frustrado a ponto de estragar meu dia. 
Essa sensibilidade me faz sentir vulner√°vel a coisas que, para muitos, talvez passassem despercebidas. Al√©m disso, 
sinto-me frequentemente triste; essa sensa√ß√£o √© uma parte significativa da minha experi√™ncia emocional e parece 
estar sempre √† espreita, pronta para me puxar para baixo quando menos espero. Sempre acho dif√≠cil me aproximar 
dos outros; sinto uma grande ansiedade ao tentar iniciar intera√ß√µes e muitas vezes evito situa√ß√µes sociais por 
causa disso. A ideia de me expor, de me colocar em situa√ß√µes sociais, me causa um desconforto enorme, ent√£o prefiro 
me distanciar, evitando o contato sempre que poss√≠vel. Tenho uma tend√™ncia a ir a excessos; frequentemente me entrego 
completamente a h√°bitos ou atividades, sem muito controle sobre os limites e consequ√™ncias. Isso pode parecer uma forma 
de escapar das emo√ß√µes, mas muitas vezes s√≥ me leva a um ciclo de exaust√£o e arrependimento.
"""

In [49]:
analysis = create_analysis(
    name="Neuroticism",
    essay=" ".join(essay_pt_br_N_high.split()),
    domain="N",
    level="high",
)

In [50]:
score_neuroticism_facets = (
    analysis.get("data")
    .get("person")
    .get("analysis")
    .get("personalities")[0]
    .get("neuroticism")
    .get("traits")
)
pd.DataFrame(score_neuroticism_facets, columns=["name", "raw_score", "percentile", "confidence"])

                   name  raw_score  percentile  confidence
0             Ansiedade  60.629434   57.631437   98.353003
1                 Raiva  67.725623   58.529057   98.478455
2            Melancolia  58.988848   46.797496   98.350542
3      Auto-Consci√™ncia  59.291577   55.499303   98.366911
4         Impulsividade  59.943455   52.646599   98.262695
5  Suscet√≠vel ao Stress  69.731802   67.591904   98.572110

### 5.2 Capture Neuroticism Low

In [51]:
essay_pt_br_N_low = """
Eu sou bem tranquilo e n√£o me deixo abalar facilmente. Mesmo quando as coisas d√£o errado, procuro manter 
a calma e resolver tudo com a cabe√ßa no lugar. N√£o sou de ficar estressado ou ansioso por qualquer coisa, 
e raramente me preocupo com problemas pequenos. Prefiro acreditar que tudo se resolve com o tempo e que n√£o 
adianta se desesperar. Tento levar a vida de boa, sem me deixar levar por emo√ß√µes negativas ou preocupa√ß√µes 
exageradas.
"""

In [52]:
analysis = create_analysis(
    name="Neuroticism",
    essay=" ".join(essay_pt_br_N_low.split()),
    domain="N",
    level="low",
)

In [53]:
score_neuroticism_facets = (
    analysis.get("data")
    .get("person")
    .get("analysis")
    .get("personalities")[0]
    .get("neuroticism")
    .get("traits")
)
pd.DataFrame(score_neuroticism_facets, columns=["name", "raw_score", "percentile", "confidence"])

                   name  raw_score  percentile  confidence
0             Ansiedade  18.583451   15.559673   92.366698
1                 Raiva  25.340261   16.283644   95.491585
2            Melancolia  15.429695    3.295812   91.340477
3      Auto-Consci√™ncia  18.856077   14.282644   94.037844
4         Impulsividade  18.812968   11.421367   87.012208
5  Suscet√≠vel ao Stress  25.890748   23.817498   96.248764

### 5.2 Capture Neuroticism Average

In [54]:
essay_pt_br_N_avg = """
Gosto de dar uma esquentada nas coisas, sim! Gosto de ter tudo sob controle, e quando algo sai dos trilhos, 
confesso que fico preocupado ou at√© mesmo ansioso e nervoso. Para mim o equilibrio n√£o existe, vou de 0 a 100 
rapidamente. Meu lado neur√≥tico e controlador acaba falando mais alto! Me sinto constantemente cansado, porque
minha mente n√£o para. Sempre fico com aquele sentimento de que estou esquecendo algo, de que deveria estar 
fazendo mais, de que o que j√° fiz n√£o foi suficiente. √â como se minha pr√≥pria mente fosse um campo minado, 
onde qualquer passo em falso pode me levar de volta para essa montanha de ansiedades e medos.
"""

In [55]:
analysis = create_analysis(
    name="Neuroticism",
    essay=" ".join(essay_pt_br_N_avg.split()),
    domain="N",
    level="avg",
)

In [56]:
score_neuroticism_facets = (
    analysis.get("data")
    .get("person")
    .get("analysis")
    .get("personalities")[0]
    .get("neuroticism")
    .get("traits")
)
pd.DataFrame(score_neuroticism_facets, columns=["name", "raw_score", "percentile", "confidence"])

                   name  raw_score  percentile  confidence
0             Ansiedade  54.241487   51.185477   98.186102
1                 Raiva  58.956434   49.808095   98.346961
2            Melancolia  53.271401   41.072775   98.184657
3      Auto-Consci√™ncia  54.365337   50.417207   98.222626
4         Impulsividade  54.330485   47.044484   98.158006
5  Suscet√≠vel ao Stress  59.774131   57.632458   98.358060